// Display labels for status values stored in English. Data keeps the original value.
// Kept free of dependencies so the server can import it too.
export const STATUS_LABELS: Record<string, string> = {
  'Active': 'Aktif',
  'Inactive': 'Nonaktif',
  'Draft': 'Draf',
  'Final': 'Final',
  'Sent': 'Terkirim',
  'Approved': 'Disetujui',
  'Rejected': 'Ditolak',
  'Quotation': 'Penawaran',
  'Sample': 'Sampel',
  'Order': 'Pesanan Baru',
  'In Production': 'Diproduksi',
  'QC': 'Lolos QC',
  'Shipping': 'Dikirim',
  'Completed': 'Selesai',
  'Cancelled': 'Dibatalkan',
  'Pending Review': 'Menunggu Tinjauan',
  'Revision Requested': 'Perlu Revisi',
  'Development': 'Dalam Pengerjaan',
  'Sent to Customer': 'Dikirim ke Pelanggan',
  'Revision': 'Revisi',
  'Queued': 'Antre',
  'In Progress': 'Dikerjakan',
  'Finishing': 'Finishing',
  'QC Passed': 'Lolos QC',
  'Requested': 'Diajukan',
  'PO Created': 'PO Dibuat',
  'Paid': 'Dibayar',
  'Shipped': 'Dikirim',
  'Received': 'Diterima',
  'Available': 'Tersedia',
  'Reserved': 'Dialokasikan',
  'In Cutting': 'Sedang Dipotong',
  'Depleted': 'Habis',
  'Spreading': 'Gelar Kain',
  'Cutting': 'Pemotongan',
  'Passed': 'Lolos',
  'Repair Needed': 'Perlu Perbaikan',
  'Verified': 'Terverifikasi',
  'Issues Found': 'Ada Masalah',
  'Accept': 'Diterima',
  'Pending Repair': 'Menunggu Perbaikan',
  'Reject Lot': 'Lot Ditolak',
  'Submitted': 'Diajukan',
  'Investigating': 'Diperiksa',
  'In Repair': 'Diperbaiki',
  'Resolved': 'Selesai',
  'Packing': 'Pengemasan',
  'Surat Jalan Dibuat': 'Surat Jalan Dibuat',
  'Sebagian': 'Sebagian',
  'Picked Up': 'Diambil Kurir',
  'In Transit': 'Dalam Perjalanan',
  'Delivered': 'Sampai Tujuan',
  'Running': 'Beroperasi',
  'Under Maintenance': 'Dalam Perawatan',
  'Broken': 'Rusak',
  'Standby': 'Siaga',
  'Compliant': 'Sesuai Standar',
  'Needs Attention': 'Perlu Tindakan',
  'On Leave': 'Cuti',
  'Resigned': 'Keluar',
  'Pending Verification': 'Menunggu Verifikasi',
  'Pending': 'Menunggu'
};

export function statusLabel(status: string | undefined | null): string {
  if (!status) return '-';
  return STATUS_LABELS[status] ?? status;
}
